version: "3.9"

services:
  frontend:
    build: ./frontend
    networks:
      - frontend_network
    ports:
      - "8080:80"

  backend:
    build: ./backend
    networks:
      - frontend_network
      - backend_network
    environment:
      - MONGO_HOST=database
      - MONGO_PORT=27017
    ports:
      - "5000:5000"

  database:
    image: mongo:latest
    networks:
      - backend_network
    ports:
      - "27017:27017"

networks:
  frontend_network:
  backend_network:
